sudo: required

language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - yarn install

before_script:
  - curl -o -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add webpack
  - export TRAVIS_COMMIT_MSG="feature $(git log --format='%h - %B' --no-merges -n 1)"
  - export TRAVIS_COMMIT_USER="$(git log --no-merges -n 1 --format=%an)"
  - export TRAVIS_COMMIT_EMAIL="$(git log --no-merges -n 1 --format=%ae)"

script:
  - yarn run build

# after_script:
#   - sh scrips/deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  secure: "$GH_TOKEN"
  on:
    branch: master

cache:
  yarn: true
  directories:
    - "node_modules"

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com:iq9891/em-fe-doc.git
